command_case = "upper_case" # or "upper_case"
enable_external_cmake_lint = true # true to use external cmake-lint
line_max_words =  80

[format]
program = "gersemi"
# Use four space indentation.
args = ["--indent", "4"]
